### ISSUE TITLE
Unable to build with hook-curl support with php 8.2 on Ubuntu 22.04

### ISSUE THREAD

**Issue by inmanturbo** [openswoole/openswoole#36]
```
In file included from /tmp/pear/temp/openswoole/ext-src/swoole_curl.cc:17:
/tmp/pear/temp/openswoole/ext-src/php_swoole_curl.h:25:10: fatal error: curl/curl.h: No such file or directory
   25 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:248: ext-src/swoole_curl.lo] Error 1
```

**Comment by erfanmola** [comment]
Try installing libcurl, eg: `sudo apt-get install libcurl4-openssl-dev`
